sprint-10: add controllers, validations
sosnin-ivan/java-filmorate pull request #1
Opened 2024-09-30 01:48 UTC by sosnin-ivan

2024-09-30 12:23 UTC, YazykovMikhail requested changes

2024-09-30 12:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Стандартный шаблон для логов
```
createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
```
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2024-09-30 12:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private long getNextId() {
Представь что у тебя 87656789 записей и что бы добавить новый фильм нужно пробежатсья по всем и вычислить максимальный идентификатор. 
Проще сделать поле которое будет отвечать за счетчик идентификаторов, как было сделано в TaskManager

2024-09-30 12:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Long id;
модификаторы доступа

2024-10-02 05:38 UTC, sosnin-ivan commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getFilms() {
добавил логгер. есть сомнения только насчет длины сообщения, мы же отдаем все фильмы, а если их 100500, вся эта масса упадет в логфайл...

2024-10-04 01:38 UTC, merged